/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppFriendsRouteImport } from './routes/_app.friends'
import { Route as AppGamesRouteImport } from './routes/_app.games'
import { Route as AppLeaderboardsRouteImport } from './routes/_app.leaderboards'
import { Route as AppPokerRouteImport } from './routes/_app.poker'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppRewardsRouteImport } from './routes/_app.rewards'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSlotsRouteImport } from './routes/_app.slots'
import { Route as AppSupportRouteImport } from './routes/_app.support'
import { Route as AppTableGamesRouteImport } from './routes/_app.table-games'
import { Route as AppVipRouteImport } from './routes/_app.vip'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminEconomyRouteImport } from './routes/admin.economy'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminGamesRouteImport } from './routes/admin.games'
import { Route as AdminLeaderboardsRouteImport } from './routes/admin.leaderboards'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminPlayersRouteImport } from './routes/admin.players'
import { Route as AdminRewardsRouteImport } from './routes/admin.rewards'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AppGamesSlugRouteImport } from './routes/_app.games.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesRoute = AppGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardsRoute = AppLeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => AppRoute,
} as any)
const AppPokerRoute = AppPokerRouteImport.update({
  id: '/poker',
  path: '/poker',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRewardsRoute = AppRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSlotsRoute = AppSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppTableGamesRoute = AppTableGamesRouteImport.update({
  id: '/table-games',
  path: '/table-games',
  getParentRoute: () => AppRoute,
} as any)
const AppVipRoute = AppVipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEconomyRoute = AdminEconomyRouteImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaderboardsRoute = AdminLeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AppGamesSlugRoute = AppGamesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppGamesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/friends': typeof AppFriendsRoute
  '/games': typeof AppGamesRouteWithChildren
  '/leaderboards': typeof AppLeaderboardsRoute
  '/poker': typeof AppPokerRoute
  '/profile': typeof AppProfileRoute
  '/rewards': typeof AppRewardsRoute
  '/settings': typeof AppSettingsRoute
  '/slots': typeof AppSlotsRoute
  '/support': typeof AppSupportRoute
  '/table-games': typeof AppTableGamesRoute
  '/vip': typeof AppVipRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/economy': typeof AdminEconomyRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/leaderboards': typeof AdminLeaderboardsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/games/$slug': typeof AppGamesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/friends': typeof AppFriendsRoute
  '/games': typeof AppGamesRouteWithChildren
  '/leaderboards': typeof AppLeaderboardsRoute
  '/poker': typeof AppPokerRoute
  '/profile': typeof AppProfileRoute
  '/rewards': typeof AppRewardsRoute
  '/settings': typeof AppSettingsRoute
  '/slots': typeof AppSlotsRoute
  '/support': typeof AppSupportRoute
  '/table-games': typeof AppTableGamesRoute
  '/vip': typeof AppVipRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/economy': typeof AdminEconomyRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/leaderboards': typeof AdminLeaderboardsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/games/$slug': typeof AppGamesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/friends': typeof AppFriendsRoute
  '/_app/games': typeof AppGamesRouteWithChildren
  '/_app/leaderboards': typeof AppLeaderboardsRoute
  '/_app/poker': typeof AppPokerRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/rewards': typeof AppRewardsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/slots': typeof AppSlotsRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/table-games': typeof AppTableGamesRoute
  '/_app/vip': typeof AppVipRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/economy': typeof AdminEconomyRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/leaderboards': typeof AdminLeaderboardsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/games/$slug': typeof AppGamesSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/friends'
    | '/games'
    | '/leaderboards'
    | '/poker'
    | '/profile'
    | '/rewards'
    | '/settings'
    | '/slots'
    | '/support'
    | '/table-games'
    | '/vip'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/economy'
    | '/admin/events'
    | '/admin/games'
    | '/admin/leaderboards'
    | '/admin/moderation'
    | '/admin/players'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/'
    | '/games/$slug'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/friends'
    | '/games'
    | '/leaderboards'
    | '/poker'
    | '/profile'
    | '/rewards'
    | '/settings'
    | '/slots'
    | '/support'
    | '/table-games'
    | '/vip'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/economy'
    | '/admin/events'
    | '/admin/games'
    | '/admin/leaderboards'
    | '/admin/moderation'
    | '/admin/players'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/support'
    | '/'
    | '/admin'
    | '/games/$slug'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_app/friends'
    | '/_app/games'
    | '/_app/leaderboards'
    | '/_app/poker'
    | '/_app/profile'
    | '/_app/rewards'
    | '/_app/settings'
    | '/_app/slots'
    | '/_app/support'
    | '/_app/table-games'
    | '/_app/vip'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/economy'
    | '/admin/events'
    | '/admin/games'
    | '/admin/leaderboards'
    | '/admin/moderation'
    | '/admin/players'
    | '/admin/rewards'
    | '/admin/settings'
    | '/admin/support'
    | '/_app/'
    | '/admin/'
    | '/_app/games/$slug'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/friends': {
      id: '/_app/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games': {
      id: '/_app/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AppGamesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboards': {
      id: '/_app/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof AppLeaderboardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/poker': {
      id: '/_app/poker'
      path: '/poker'
      fullPath: '/poker'
      preLoaderRoute: typeof AppPokerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rewards': {
      id: '/_app/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AppRewardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/slots': {
      id: '/_app/slots'
      path: '/slots'
      fullPath: '/slots'
      preLoaderRoute: typeof AppSlotsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/table-games': {
      id: '/_app/table-games'
      path: '/table-games'
      fullPath: '/table-games'
      preLoaderRoute: typeof AppTableGamesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vip': {
      id: '/_app/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof AppVipRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/economy': {
      id: '/admin/economy'
      path: '/economy'
      fullPath: '/admin/economy'
      preLoaderRoute: typeof AdminEconomyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaderboards': {
      id: '/admin/leaderboards'
      path: '/leaderboards'
      fullPath: '/admin/leaderboards'
      preLoaderRoute: typeof AdminLeaderboardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/players': {
      id: '/admin/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/games/$slug': {
      id: '/_app/games/$slug'
      path: '/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof AppGamesSlugRouteImport
      parentRoute: typeof AppGamesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppGamesRouteChildren {
  AppGamesSlugRoute: typeof AppGamesSlugRoute
}

const AppGamesRouteChildren: AppGamesRouteChildren = {
  AppGamesSlugRoute: AppGamesSlugRoute,
}

const AppGamesRouteWithChildren = AppGamesRoute._addFileChildren(
  AppGamesRouteChildren,
)

interface AppRouteChildren {
  AppFriendsRoute: typeof AppFriendsRoute
  AppGamesRoute: typeof AppGamesRouteWithChildren
  AppLeaderboardsRoute: typeof AppLeaderboardsRoute
  AppPokerRoute: typeof AppPokerRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRewardsRoute: typeof AppRewardsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSlotsRoute: typeof AppSlotsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTableGamesRoute: typeof AppTableGamesRoute
  AppVipRoute: typeof AppVipRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFriendsRoute: AppFriendsRoute,
  AppGamesRoute: AppGamesRouteWithChildren,
  AppLeaderboardsRoute: AppLeaderboardsRoute,
  AppPokerRoute: AppPokerRoute,
  AppProfileRoute: AppProfileRoute,
  AppRewardsRoute: AppRewardsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSlotsRoute: AppSlotsRoute,
  AppSupportRoute: AppSupportRoute,
  AppTableGamesRoute: AppTableGamesRoute,
  AppVipRoute: AppVipRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminEconomyRoute: typeof AdminEconomyRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGamesRoute: typeof AdminGamesRoute
  AdminLeaderboardsRoute: typeof AdminLeaderboardsRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminPlayersRoute: typeof AdminPlayersRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminEconomyRoute: AdminEconomyRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminGamesRoute: AdminGamesRoute,
  AdminLeaderboardsRoute: AdminLeaderboardsRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminPlayersRoute: AdminPlayersRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
